name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_NAME: "docker.io"
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
  IMAGE_NAME: "docker.io/kalenpeterson/dgx-chargeback"

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
        logout: true

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "${{ env.IMAGE_NAME }}:${{ github.run_number }},${{ env.IMAGE_NAME }}:latest"
